language: go

go:
- "1.11"

install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- pip install aws-sam-cli

before_script:
- sam --version

script:
- make

after_success:
- bash <(curl -s https://codecov.io/bash)
