language: go

go:
- "1.11"

install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
- make

after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- mv ./main "main-v$TRAVIS_TAG"

deploy:
  provider: releases
  api_key:
    secure: "KyL29ac0cBVXYrcRNzIWzbO1VCVhmIQ6dlZ6kmZiS/wG2oPnslxDu2DAm4Nie7FxQbzI68JhFAg33sZRyRmfU1b2G/Rg6MfoJP5szVmoab2sEUPGKdW+1Imh1D9zxTr/l4N7jKMZmN0oH6lSsFbnnXjcHRAOQfsmpPry29UtZNlT6X3S7eoLrGQ5XoVxCPvGZD3FFSwyYkcE3TGb4U9qdfByN/i67QAf3Y5zmBGhajHOpgNKH4V78EvZ5W1wfiOCJn6hDkV7SfiVLRLfws1wL5nHi2WEXxpdgiJRQ5gekXuGxVQ1Ec/p+40nzleNQH4zxtQNk71AgnszGdzYPMGzSraIxfAvUHMiCsLymk5C8pKsFmvNcxzzMEO6Lj5OVovyE+DFzT9VvsL8+Myc9yoRCyZASLmqKO2Rxp4+65ysste2O3GpRCZWRoReb5yEu/kzvGcjqM7zXGXmGkQLbde7jSt+T/Ni7GEO7qVyYrZAv0oPwZoRQnwAFNrH8NsDrrTIslr2PYAZd1u4wBeMxHbn5O7UG989YvYvtNpmPCY4yoiFpN7KujDiw4TqkC5OhzVfTv1o2SNQDIdzXSE4SujLDSXjjJr6dTga2l0mu/XcoYYhmvJcBc1hPlq3dP/HYqjG4uF1TkX/GXTZ9PM3d94zyXf47Mwpwdo1TfDjLDHFem4="
  file: "main-v$TRAVIS_TAG"
  on:
    repo: s12v/aws-alb-firehose
    tags: true
